# Transient /etc is _disabled_ (the default) as enabling it produces issues such
# as https://github.com/bootc-dev/bootc/discussions/1435.
FROM quay.io/fedora/fedora-bootc:43

COPY remove.txt /
COPY install.txt /

RUN <<EOF
dnf remove  --assumeyes --quiet $(<remove.txt) >/dev/null
dnf install --assumeyes --quiet $(<install.txt) >/dev/null
rm {remove,install}.txt
EOF

# Services to disable and enable. For some reason systemd presets don't seem to
# get picked up, so we have to enable/disable services the traditional way.
RUN <<EOF
systemctl disable \
    bootc-fetch-apply-updates.timer \
    bootc-fetch-apply-updates.service

systemctl mask \
    bootc-fetch-apply-updates.timer \
    bootc-fetch-apply-updates.service

systemctl enable sshd
EOF

RUN <<EOF
dnf clean all
rm -rf /var/{cache,log}/*
rm -rf /var/lib/dnf
rm -rf /root/*
EOF

COPY overlay/ /

RUN bootc container lint
