# Transient /etc is _disabled_ (the default) as enabling it produces issues such
# as https://github.com/bootc-dev/bootc/discussions/1435.
FROM quay.io/fedora/fedora-bootc:43

RUN <<EOF
dnf install --assumeyes --quiet \
    fastfetch \
    firewalld \
    htop \
    zram-generator-defaults \
    >/dev/null

# These packages aren't necessary so we remove them in order to reduce the
# image/container size.
dnf remove  --assumeyes --quiet \
    amd-gpu-firmware \
    gssproxy \
    nvidia-gpu-firmware \
    python3-botocore \
    qemu-user-static \
    qemu-user-static-aarch64 \
    qemu-user-static-alpha \
    qemu-user-static-arm \
    qemu-user-static-hexagon \
    qemu-user-static-hppa \
    qemu-user-static-loongarch64 \
    qemu-user-static-m68k \
    qemu-user-static-microblaze \
    qemu-user-static-mips \
    qemu-user-static-or1k \
    qemu-user-static-ppc \
    qemu-user-static-riscv \
    qemu-user-static-s390x \
    qemu-user-static-sh4 \
    qemu-user-static-sparc \
    qemu-user-static-x86 \
    qemu-user-static-xtensa \
    udisks2 \
    >/dev/null
EOF

RUN <<EOF
# Services to disable and enable. For some reason systemd presets don't seem to
# get picked up, so we have to enable/disable services the traditional way.
systemctl disable \
    bootc-fetch-apply-updates.timer \
    bootc-fetch-apply-updates.service

systemctl mask \
    bootc-fetch-apply-updates.timer \
    bootc-fetch-apply-updates.service

systemctl enable sshd
systemctl enable firewalld
EOF

RUN <<EOF
# Clean up temporary files we don't want in the image.
dnf clean all
rm -rf /var/{cache,log}/*
rm -rf /var/lib/dnf
rm -rf /root/*

# Documentation and unused locales aren't necessary on a server.
rm -rf /usr/share/{man,doc}/*
mv /usr/share/locale/{en,en_US} /tmp
rm -rf /usr/share/locale/*
mv /tmp/{en,en_US} /usr/share/locale
EOF

COPY overlay/ /

RUN bootc container lint
